name: AWS Lambda Deploy
uses: appleboy/lambda-action@v0.1.5

on:
  push:
    branches:
      - main
jobs:
  deploy-source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name:  Use Node.js 12.x
      uses: actions/setup-node@v1.4.2
      with:
          node-version: [12.x]
    - name: Install dependencies, Build application and Zip dist folder contents
      run: npm install && npx tsc && zip -qq -r -j ./lambda.zip ./dist/*  
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Lambda-api
        zip_file: lambda.zip  
